### ISSUE TITLE
add progress messages for long running functions like summarizeLargeScaleCharacteristics

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/CohortCharacteristics#1]
summarizeLargeScaleCharacteristics has multiple for loops. We can add progress messages whenever we have for loops that let the user know approximately what percentage of the work has been completed. 

Maybe something like this https://github.com/darwin-eu-dev/CDMConnector/blob/b219f57eb8c519c322c738076e8bd26903f7895e/R/generateCohortSet.R#L291

It's helpful to know if it the function is likely to run for anther few minutes or several hours.

**Comment by edward-burn** [comment]
Added in https://github.com/darwin-eu-dev/CohortCharacteristics/pull/34
