### ISSUE TITLE
Export a graph from plotCohortAttrition()

### ISSUE THREAD

**Issue by martaalcalde** [darwin-eu-dev/CohortCharacteristics#115]
To export a graph (output from `plotCohortAttrition()`) as a .png I have to currently do this:

```
attrition |> plotCohortAttrition(1) |> export_svg() %>% charToRaw %>% rsvg_png("graph.png", width = 2000)
```

It would be nice if there was a more user-friendly way to do it!

**Comment by catalamarti** [comment]
this has been already done
