### ISSUE TITLE
Feature request: plotCohortAttrition() work with an attrition table

### ISSUE THREAD

**Issue by martaalcalde** [darwin-eu-dev/CohortCharacteristics#120]
I think it would be nice if plotCohortAttrition() work with both: a summarised result and an attrition table

**Comment by catalamarti** [comment]
we can add inside:

if (inherits(result, "cohort_table")) {
  result <- summariseCohortAttrition(result)
}

if (all(omopgenerics::cohortColumns("cohort_attrition") %in% colnames(result))) {
  -> convert to a summarised result
}
