### ISSUE TITLE
test tableLSC performance

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/CohortCharacteristics#205]

**Comment by edward-burn** [comment]
library(CohortCharacteristics)
db <- DBI::dbConnect(RPostgres::Postgres(),
                     dbname = Sys.getenv("CDM5_POSTGRESQL_DBNAME"),
                     host = Sys.getenv("CDM5_POSTGRESQL_HOST"),
                     user = Sys.getenv("CDM5_POSTGRESQL_USER"),
                     password = Sys.getenv("CDM5_POSTGRESQL_PASSWORD"))
cdm <- CDMConnector::cdm_from_con(
  con = db,
  cdm_schema = Sys.getenv("CDM5_POSTGRESQL_CDM_SCHEMA"),
  write_schema = c(schema =  Sys.getenv("CDM5_POSTGRESQL_SCRATCH_SCHEMA"),
                   prefix = "incp_"),
  achilles_schema = Sys.getenv("CDM5_POSTGRESQL_CDM_SCHEMA")
)

cdm$asthma <- CohortConstructor::conceptCohort(cdm = cdm,
                                               conceptSet = list("asthma" = 317009),
                                               name = "asthma")

lsc <- summariseLargeScaleCharacteristics(cdm$asthma, 
                                          eventInWindow = "condition_occurrence")

tictoc::tic()
tableLargeScaleCharacteristics(lsc)
tictoc::toc()

**Comment by catalamarti** [comment]
I've done a check and it takes:
0.1 seconds to perform checks inside `tableLargeScaleCharacteristics()`
0.6 seconds inside `visOmopResults::visOmopTable()`
and 37 seconds to do the visualisation, so it is more related to a `gt` issue than to `CohortCharacteristics` or `visOmopResults`

<img width="328" alt="Screenshot 2024-09-30 at 14 13 46" src="https://github.com/user-attachments/assets/8de4449c-1638-4c85-a9d8-a5f4d55bb8d6">
