### ISSUE TITLE
plotCohortAttrition to work also with summariseCohortAttrition

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/CohortCharacteristics#81]
hi @martaalcalde would you be happy if I make all this to work?

```
cdm$cohort |> attrition() |> plotCohortAttrition()
cdm$cohort |> summariseCohortAttrition() |> plotCohortAttrition()
cdm$cohort |> summary() |> plotCohortAttrition()
cdm$cohort |> plotCohortAttrition()
```

The last one is the only one I am not so sure about, what do you think?

@edward-burn happy too?

**Comment by martaalcalde** [comment]
Yes, very happy

**Comment by edward-burn** [comment]
Let's discuss, because ideally all plot functions would have the same workflow

**Comment by edward-burn** [comment]
Discussed and decided these are the only two to support:
- cdm$cohort |> summariseCohortAttrition() |> plotCohortAttrition()
- cdm$cohort |> summary() |> plotCohortAttrition()
